name: C

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]

    runs-on: ${{matrix.os}}

    steps:
    - uses: actions/checkout@v3
    - uses: actions/setup-python@v2
    - uses: BSFishy/meson-build@v1.0.3
      with:
        meson-version: 0.64.1
        action: test
