name: C

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    strategy:
      matrix:
        include:
          - os: ubuntu-latest
            asan: "-Db_sanitize=address"
            cc: "gcc"
          - os: macos-latest
            asan: ""
            cc: "clang"
          - os: windows-latest
            asan: ""
            cc: "cl"

    runs-on: ${{matrix.os}}

    env:
      CC: ${{matrix.cc}}

    steps:
    - uses: actions/checkout@v3
    - uses: actions/setup-python@v2
    - uses: BSFishy/meson-build@v1.0.3
      with:
        meson-version: 0.64.1
        action: test
        setup-options: ${{matrix.asan}}
