name: C

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    strategy:
      matrix:
        os: [""]
        asan: [false]
        include:
          - os: ubuntu-latest
            asan: "-Db_sanitize=address"
          - os: macos-latest
            asan: ""
          - os: windows-latest
            asan: ""

    runs-on: ${{matrix.os}}

    steps:
    - uses: actions/checkout@v3
    - uses: actions/setup-python@v2
    - uses: BSFishy/meson-build@v1.0.3
      with:
        meson-version: 0.64.1
        action: test
        setup-options: ${{matrix.asan}}
